### ISSUE TITLE
doesn't work with .table-striped

### ISSUE THREAD

**Issue by drKnoxy** [iKristjan/bootstrap-responsive-table-scrolling-shadows#1]

**Comment by iKristjan** [comment]
Yeah, you're right @drKnoxy, by default it doesn't.
Unfortunately the striped background hides the shadow in the background.
So, I've been using a hack which works pretty well actually.

The trick is to use an 20% opacity on the stripe background color, so you can still see the background shadow through the stripe. This should work fine for the default color stripes, but if you use a custom color you should change the color accordingly.

```
.table-responsive > .table-striped > tbody > tr:nth-of-type(odd) {
  background-color: rgba(225, 225, 225, .2);
}
```
